
CREATE TABLE netflix
(
    show_id      VARCHAR(5),
    type         VARCHAR(10),
    title        VARCHAR(250),
    director     VARCHAR(550),
    casts        VARCHAR(1050),
    country      VARCHAR(550),
    date_added   VARCHAR(55),
    release_year INT,
    rating       VARCHAR(15),
    duration     VARCHAR(15),
    listed_in    VARCHAR(250),
    description  VARCHAR(550)
);


SELECT * FROM netflix;
SELECT
	count(*) AS total_content
FROM netflix;



SELECT
	DISTINCT TYPE
FROM netflix;


-- BUSINESS PROBLEMS --
-- Q1. COUNT THE NUMBER OF MOVIES Vs TV SHOWS

SELECT
	TYPE,
	COUNT(*) AS total_content
FROM netflix
GROUP BY TYPE;

-- HERE ARE TOTAL 6131 MOVIES NAD 2676 TV SHOWS


-- Q2. FIND THE MOST COMMON RATING  FOR MOVIES AND TV SHOWS

SELECT
	type,
	rating,
	COUNT(*)
FROM netflix
GROUP BY 1,2
ORDER BY 3 DESC;


-- THE MOST COMMON RATING IS TV-MA(2062) AND TV-14(1427)


-- Q3. LIST ALL MOVIES RELEASED IN A SPECIFIC YEAR 2020


SELECT*FROM netflix
WHERE
	type = 'Movie'
	AND
	release_year = 2020;

-- TOTAL 517 MOVIES RELEASED UN YEAR 2020

-- Q4. FIND THE TOP CONTRIES WITH THE TOP CONTENT ON NETFLIX

SELECT
		UNNEST(STRING_TO_ARRAY(country,',')) AS new_country,
	COUNT(show_id) AS toral_contant
fROM netflix
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;


-- UNITED STATE(3211) AND INDIA(1008) HAVE THE MOST NUMBER OF CONTENT ON NETFLIX


-- Q5. IDENTIFY THE LONGEST MOVIE

SELECT*FROM netflix
WHERE
	TYPE = 'Movie'
	AND
	duration = (SELECT MAX(duration) FROM netflix);

-- 99 MIN IS THE LONGEST DURATION

-- Q6. FIND CONTENT ADD IN LAST 5 YEAR


SELECT 
	*
FROM netflix
WHERE
	 TO_DATE(date_added,'Month DD, YYYY')>= CURRENT_DATE - INTERVAL '5 YEARS';

-- THIS THE CONTENT ADD IN LAST 5 YEAR

-- Q7. FIND ALL THE MOVIES AND TV SHOWS  BY DAIRECTOR 'RAJIV CHILAKA'


SELECT * FROM netflix
WHERE
	director LIKE  '%Rajiv Chilaka%';


	-- TOTAL 22 MOVIES AND TV SHOWS DIRECTED BY 'RAJIV CHILAKA(INCLUDING WITH OTHER DIRECTOR ALSO)'


-- Q8. LIST ALL TV SHOWS WITH MORE THAN 5 SEASON

SELECT
	*
FROM netflix
WHERE
	type = 'TV Show'
	AND
	SPLIT_PART(duration, ' ', 1)::numeric > 5;

--  99 TV SHOW HAS MORE THEN 5 SESSIONS

-- Q9. COUNT THE NUMBER OF CONTENT ITEMS IN EACH GENRE

SELECT
	UNNEST(STRING_YO_ARRAY(listed_in, ',')) AS genre,
	COUNT(show_id) 	AS total_content
FROM netflix
GROUP BY 1;

-- 73 NUMER OF CONTENT


-- Q10. FIND EACH YEAR AND RHE AVERAGE NUMBER OF CONTENT RELEASED BY IN ON NETFLIX,
-- RETURNT TOP 5 YEAR WITH HIGHEST AVERAGE CONTANT RELEASE.


SELECT
	EXTRACT(YEAR FROM TO_DATE(date_added, 'Month, DD, YYYY')) AS year,
	COUNT (*)
FROM netflix
WHERE country = 'India'
GROUP BY 1;


-- INDIA RELEASED MOST CONTANT ON NETFLIX IN 2018 THE NUMBER IS (333) WITH THE AVG OF 34.26



-- Q11. LIST ALL MOVIES THT ARE DOCUMENTARIES

SELECT * FROM netflix
WHERE
listed_in ILIKE '%Documentaries%'


-- 869 MOVIES ARE THE DOCUMENTARIES

-- Q12. FIND ALL THE CONTENT WITHOUT A DIRECTOR


SELECT * FROM netflix
WHERE
	director IS NULL;


-- 2634  IS THE CONTENT WITHOUT A DIRECTOR

-- Q13. FIND ANY MOVIES ACTOR ' SALMAN KHAN ' APPEARED IN LAST 10 YEARS

SELECT *  FROM netflix
WHERE
	casts ILIKE '%Salman Khan%'

--  THERE ARE 20 MOVIES APPEARANCE BY SALAM KHAN LAST 10 YEAR

--  Q14. FIND THE TOP 10 ACTOR(INDIA) WHO APPEARED IN HIGHEST NUMBER OF MOVIES IN LAST 10  YEAR


SELECT
-- show_id,
-- casts,
UNNEST(STRING_TO_ARRAY(casts, ',')) AS actors,
COUNT(*) AS total_content
FROM netflix
WHERE country ILIKE 'India'
GROUP BY 1
ORDER BY 2 DESC;


-- TOP 10 ACTORS FROM INDIA APPEARED MOST ARE ANUPAM KHER(39), SHAH RUKH KHAN(24),
--  PARESH RAWAL(24), OM PURI(23), AKSHAY KUMAR(22), BOMAN IRANI(21), AMITABH BACHCHAN(20),
-- KARENA KAPOOR(19) AND NASEERUDDIN SHAH(19)


-- Q15. 

